services:
  front-end:
    profiles: ["full"]
    container_name: front-end
    build:
      context: ..\front-end
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      AUTH_URL: ${AUTH_URL}
      AUTH_SIGNOUT_URL: ${AUTH_SIGNOUT_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
      KEYCLOAK_END_SESSION_ENDPOINT: ${KEYCLOAK_END_SESSION_ENDPOINT}
    ports:
      - 3000:3000
    depends_on:
      - api-gateway
      - keycloak
    networks:
      - frontend_net
      - keycloak_net

  api-gateway:
    profiles: ["full", "backend"]
    hostname: api-gateway
    container_name: api-gateway
    build:
      context: ..\api-gateway
      dockerfile: Dockerfile
    ports:
      - 7200:8080
      - 7201:8081
    depends_on:
      - whiteboard-service
    networks:
      - frontend_net
      - api_net

  whiteboard-service:
    profiles: ["full", "backend"]
    hostname: whiteboard-service
    container_name: whiteboard-service
    build:
      context: ..\whiteboard-service
      dockerfile: Dockerfile
    ports:
      - 7210:80
    environment:
      - ConnectionStrings__Npgsql=${WB_CONNECTION_STRING}
    depends_on:
      - whiteboard-db
    networks:
      - whiteboard_net
      - api_net
      - rabbitmq_net

  whiteboard-db:
    profiles: ["full", "backend", "dev"]
    container_name: whiteboard-db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${WB_DB}
      POSTGRES_USER: ${WB_USERNAME}
      POSTGRES_PASSWORD: ${WB_PASSWORD}
    ports:
      - 7215:5432
    volumes:
      - whiteboard-db-data:/var/lib/postgresql/data
      - ./config/whiteboard/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - whiteboard_net

  session-handler:
    profiles: ["full", "backend"]
    container_name: session-handler
    build:
      context: ..\session-handler
      dockerfile: Dockerfile
    # environment:
    ports:
      - 7220:8080
      - 7221:8081
    depends_on:
      - session-db
      - session-redis
    networks:
      - session_net
      - api_net
      - rabbitmq_net

  session-redis:
    profiles: ["full", "backend", "dev"]
    container_name: redis-handler
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PW}
    ports:
      - 7225:6379
      - 8001:8001
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      # - /local-data/:/data
      - session-redis-data:/data
    networks:
      - session_net

  session-db:
    profiles: ["full", "backend", "dev"]
    container_name: session-db
    image: mongodb/mongodb-community-server
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=badmin
      - MONGO_INITDB_DATABASE=boardcontents
    ports:
      - 7226:27017
    volumes:
      - session-db-data:/data/db

  #   container_name: session-db
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: ${SB_DB}
  #     POSTGRES_USER: ${SB_USERNAME}
  #     POSTGRES_PASSWORD: ${SB_PASSWORD}
  #   ports:
  #     - 7226:5432
  #   volumes:
  #     - session-db-data:/var/lib/postgresql/data
  #     - ./config/session/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - session_net
  

  keycloak:
    profiles: ["full", "backend", "dev"]
    hostname: keycloak
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: -v start-dev --import-realm
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - 8080:8080
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import
      - keycloak-db-data:/opt/jboss/keycloak/standalone/data
    depends_on:
      - keycloak-db
    networks:
      - keycloak_net
      - api_net
      - frontend_net

  keycloak-db:
    profiles: ["full", "backend", "dev"]
    container_name: keycloak-db
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: postgres
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready --username=postgres --dbname=keycloak"]
        interval: 5s
        timeout: 5s
        retries: 3
    networks:
      - keycloak_net

  rabbitmq:
    profiles: ["full", "backend", "dev"]
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin  
      RABBITMQ_DEFAULT_PASS: badmin 
    networks:
      - rabbitmq_net

networks:
  frontend_net:
    driver: bridge
  api_net:
    driver: bridge
  whiteboard_net:
    driver: bridge
  session_net:
    driver: bridge
  keycloak_net:
    driver: bridge
  rabbitmq_net:
    driver: bridge

volumes:
  keycloak-db-data:
  whiteboard-db-data:
  session-db-data:
  session-redis-data: