apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-service-deployment
  labels:
    app: whiteboard-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whiteboard-service
  template:
    metadata:
      labels:
        app: whiteboard-service
    spec:
      containers:
      - name: whiteboard-service
        image: cloudbordcontainer.azurecr.io/whiteboard-service:latest
        ports:
        - containerPort: 80
          hostPort: 33077
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-cloudbord-kv"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-cloudbord-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "a8f17b6b-03fb-4c78-b797-c6e16332b568"
    keyvaultName: "cloudbord-kv"
    objects:  |
      array:
        - |
          objectName: ConnectionString-BoardsDB
          objectType: secret
          objectVersion: ""
    tenantId: "0172c9f5-f568-42ac-9eb8-24ef84881faa"
---
apiVersion: v1
kind: Service
metadata:
  name: whiteboard-loadbalancer
spec:
  selector:
    app: whiteboard-service-deployment
  ports:
  - protocol: TCP
    port: 33077
    targetPort: 80
  type: LoadBalancer