services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: postgres
    volumes:
      - kc-data:/var/lib/postgresql/data
    networks:
      - auth
    
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - 8080:8080
    command: -v start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./config:/opt/keycloak/data/import
      - kc-data:/opt/jboss/keycloak/standalone/data
    depends_on:
      - keycloak-db
    networks:
      - auth

networks:
  auth:

volumes:
  kc-data: