apiVersion: v1
kind: Service
metadata:
  name: session-redis
spec:
  ports:
    - name: "7225"
      port: 7225
      targetPort: 6379
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    app: session-redis
