apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: session-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-redis
  serviceName: session-redis
  template:
    metadata:
      labels:
        app: session-redis
    spec:
      containers:
        - name: session-redis
          image: redis/redis-stack:latest
          livenessProbe:
            exec:
              command:
                - --requirepass
                - redis-cli
                - --raw
                - incr
                - ping
          ports:
            - containerPort: 6379
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: session-redis-data
      restartPolicy: Always
      volumes:
        - name: session-redis-data
          persistentVolumeClaim:
            claimName: session-redis-data
