apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --profile full -o kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: whiteboard-service
  name: whiteboard-service
spec:
  ports:
    - name: "7210"
      port: 7210
      targetPort: 80
  selector:
    io.kompose.service: whiteboard-service
