apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whiteboard-service
  template:
    metadata:
      labels:
        app: whiteboard-service
    spec:
      containers:
        - name: whiteboard-service
          image: cloudbordcontainer.azurecr.io/whiteboard-service
          ports:
            - containerPort: 80
              protocol: TCP
          # volumeMounts:
          # - name: secrets-store-inline
          #   mountPath: "/mnt/secrets-store"
          #   readOnly: true
          env:
            - name: KV_URL
              valueFrom:  
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: KV_URL
            - name: ConnectionStrings__Npgsql
              valueFrom:
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: DB_CONNECTION_STRING
            - name: ConnectionStrings__RabbitMQ
              valueFrom:
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: RB_CONNECTION_STRING
            - name: Jwks__Url
              valueFrom:
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: JWKS_URL
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: JWT_AUDIENCE
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: JWT_ISSUER
            - name: RabbitMQ__HostName
              valueFrom:
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: RABBIT_HOST
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: RABBIT_PASS
            - name: RabbitMQ__Port
              valueFrom:
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: RABBIT_PORT
            - name: RabbitMQ__UserName
              valueFrom:
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: RABBIT_USER
      # volumes:
      # - name: secrets-store-inline
      #   csi:
      #     driver: secrets-store.csi.k8s.io
      #     readOnly: true
      #     volumeAttributes:
      #       secretProviderClass: "azure-cloudbord-kv"
      hostname: whiteboard-service
      restartPolicy: Always
