apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --profile full -o kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: whiteboard-service
  name: whiteboard-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: whiteboard-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --profile full -o kube
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: whiteboard-service
    spec:
      containers:
        - name: whiteboard-service
          image: cloudbordcontainer.azurecr.io/whiteboard-service
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          env:
            - name: KV_URL
              valueFrom:  
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: KV_URL
            - name: ConnectionStrings__Npgsql
              valueFrom:
                secretKeyRef:
                  name: whiteboard-service-secrets
                  key: DB_CONNECTION_STRING
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-cloudbord-kv"
      hostname: whiteboard-service
      restartPolicy: Always
