apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --profile full -o kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: session-handler
  name: session-handler
spec:
  ports:
    - name: "7220"
      port: 7220
      targetPort: 8080
    - name: "7221"
      port: 7221
      targetPort: 8081
  selector:
    io.kompose.service: session-handler
