apiVersion: v1
kind: Service
metadata:
  name: session-handler
spec:
  ports:
    - name: "7220"
      port: 7220
      targetPort: 8080
    - name: "7221"
      port: 7221
      targetPort: 8081
  selector:
    name: session-handler
