apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: session-handler-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: session-handler
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
