apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-handler
spec:
  replicas: 2
  selector:
    matchLabels:
      name: session-handler
  template:
    metadata:
      labels:
        name: session-handler
    spec:
      containers:
        - image: cloudbordcontainer.azurecr.io/session-handler
          name: session-handler
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 200Mi
      restartPolicy: Always
