apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --profile full -o kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: session-handler
  name: session-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: session-handler
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --profile full -o kube
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: session-handler
    spec:
      containers:
        - image: cloudbordcontainer.azurecr.io/session-handler
          name: session-handler
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
