apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --profile full -o kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "7200"
      port: 7200
      targetPort: 8080
    - name: "7201"
      port: 7201
      targetPort: 8081
  selector:
    io.kompose.service: api-gateway
