apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --profile full -o kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: keycloak-db
  name: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --profile full -o kube
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: keycloak-db
    spec: 
      containers:
        - env:
            - name: POSTGRES_USER
              valueFrom:  
                secretKeyRef:
                  name: keycloak-db-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:  
                secretKeyRef:
                  name: keycloak-db-secrets
                  key: POSTGRES_PASSWORD
          image: postgres:latest
          livenessProbe:
            exec:
              command:
                - pg_isready --username=postgres --dbname=keycloak
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          name: keycloak-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: keycloak-db-data
      restartPolicy: Always
      volumes:
        - name: keycloak-db-data
          persistentVolumeClaim:
            claimName: keycloak-db-data
