CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Boards" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OwnerId" bigint NOT NULL,
    "Name" text NOT NULL,
    "MemberIds" bigint[] NOT NULL,
    CONSTRAINT "PK_Boards" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240526180735_InitialCreate', '8.0.5');

COMMIT;