CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Boards" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OwnerId" uuid NOT NULL,
    "Name" text NOT NULL,
    "MemberIds" uuid[] NOT NULL,
    CONSTRAINT "PK_Boards" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240615191510_InitialCreate', '8.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "Boards" ADD "BoardContents" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240618214956_AddBoardContentsToBoard', '8.0.6');

COMMIT;