apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --profile full -o kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: front-end
  name: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: front-end
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --profile full -o kube
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: front-end
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: front-end-secrets
          image: cloudbordcontainer.azurecr.io/front-end
          name: front-end
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
      restartPolicy: Always
